config/routes.rb
Rails.application.routes.draw do

  resources :user_positions
  get 'customer_advisor/index'
  get 'customer_advisor/index2'
  
  get 'listaccounts/index'

  get 'statement/index'

  resources :transactions
  resources :accounts
  resources :emails
  resources :appointment_documents
  resources :service_documents
  resources :appointments
  resources :advisors
  resources :partner_links
  get 'ticketuserview/index'
  get 'ticketuserview/index2'
  get 'users/ticketstatus'

  resources :user_tickets
  resources :tickets
  resources :customers
  get 'showcal/action'

  get 'showcal/bid'

  get 'showcal/event'

  resources :bid_documents
  resources :hs_ratings
  resources :hotspot_details
  resources :hotspots
  resources :favourits
  get 'ticker/index'

  resources :appparams
  get 'offer/index'
  get 'home/index2'
  get 'home/index3'
  get 'home/index4'
  get 'home/index5'
  get 'home/index6'  
  get 'home/index7'  
  resources :webmasters
  resources :bid_details
  resources :bids
  resources :jobs
  resources :donation_stats
  resources :donation_details
  resources :donations
  resources :sponsors
  resources :event_details
  resources :events
  devise_for :users, :controllers => {registrations: 'registrations'}

  resources :companies
  resources :users
  resources :searches
  resources :services
  resources :calenders
  resources :vehicles
  resources :request_details
  resources :requests
  resources :ratings
  resources :searches

  root 'home#index3'
  get 'admin/sendmail'
  get 'admin/showmap'
  get 'home/index'
  post 'home/index'
  get 'home/dashboard'
  post 'home/dashboard'
  get 'users/index' 
  get 'users/workorder'
  get 'companies/search'
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
    @stat_user = User.select("date(created_at) as datum, count(id) as summe").group("date(created_at)")
    @stat_company = Company.select("date(created_at) as datum, count(id) as summe").group("date(created_at)")
    
  if user_signed_in?
    #redirect_to current_user
  end
end
def index2
    @users = User.all.order(last_sign_in_at: :desc).page(params[:page]).per_page(20)
    @usanz = @users.count
end

def index3
end

def index4
    @users = User.all.last
    @hash = Gmaps4rails.build_markers(@users) do |user, marker|
      if user.latitude != nil and user.longitude != nil
        marker.lat user.latitude
        marker.lng user.longitude
        marker.infowindow "<a href=/users/" + user.id.to_s + ">" + user.name + "</a>"
        if user.avatar 
          marker.picture :url => url_for(user.avatar(:small)), :width => 50, :height => 50
        else
          marker.picture :url => "http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=%E2%80%A2|", :width => 50, :height => 50
        end
      end
     end
     @hash.push({lat: request.location.latitude, lng: request.location.longitude, infowindow: "img src="+url_for(User.find(1).avatar(:small)) })

@user = current_user
@lat = request.location.latitude
@lng = request.location.longitude 
@text = @lat.to_s + "/" + @lng.to_s
end

def index5
  @test = DonationStat.select("date(created_at) as datum, count(amount) as summe").group("date(created_at)")

  @array = []
  @cat = Category.all
  @cat.each do |c|
    anz = Company.where('category_id=?', c.id).count
    if anz > 0
      hash = Hash.new
      hash = {"label" => c.name, "value" => anz}
      @array << hash
    end
  end
  
  @array.each do |a|
    puts a.to_s
  end
  
end

  def index6
    @user=User.find(current_user.id)
    @user = User.find(2)
  end

end

app/helpers/home_helper.rb
module HomeHelper

end

app/views/home/index2.html.erb
<div class="container-fluid">
	<div class="row">
    <div class="col-md-12">
      <div class="panel-heading header">
        <li_header>
        USER STAT
        <span class="badge"><%= @usanz %></span>
        </li_header>
      </div>
    </div>
  </div>
	<div class="row">
    <div class="col-md-12">
  		<table class="table table-striped">
        <thead>
          <tr>
            <td colspan="3">
              <div class="digg_pagination">
                  <%= will_paginate @users, :container => false, previous_label: "<", next_label: ">" %>
              </div>	  
            </td>
          </tr>
          <tr>
            <th>Name</th>
            <th>last location</th>
            <th>letzte Anmeldung</th>
            <th>Anzahl Anmeldungen</th>
          </tr>
        </thead>
        <tbody>
            <% @users.each do |u| %>
              <tr>
    				    <td>
    				      <anzeigetext>
    				      <%= u.name + " " + u.lastname %>
                  </anzeigetext><br>
                  <%= u.email %>
                </td>
                <td>
                  not implemented yet
                </td>
                <td>
                  <%= u.last_sign_in_at.strftime("%d.%m.%Y-%T") if u.last_sign_in_at != nil %>
                </td>
                <td>
                  <%= u.sign_in_count %>
                </td>
              </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/home/index3.html.erb
  <div class="row">
    <header>
    <%= header("xConnect", true) %>
    </header>
  </div>
  <div class="row">
      <div class='col-xs-12'>
          <div class="panel-body">

            <%= build_kachel("Abfragen",home_index6_path, "question-sign", true) %>
            <%= build_kachel("LocateMe",new_user_position_path, "globe", true) %>
            <%= build_kachel("Privatpersonen",users_path, "user", false) %>
            <%= build_kachel("Firmen",companies_path, "copyright-mark", false) %>
            <%= build_kachel("Angebote",services_path, "shopping-cart", false) %>
            <%= build_kachel("Aktionen",services_path, "time", false) %>
            <%= build_kachel("ShareMe",vehicles_path, "retweet", false) %>
            <%= build_kachel("Ausschreibungen",bids_path, "pencil", false) %>
            <%= build_kachel("Stellenanzeigen",jobs_path, "briefcase", false) %>
            <%= build_kachel("Veranstaltungen",events_path, "glass", false) %>
            <%= build_kachel("Ausflugsziele",hotspots_path, "camera", false) %>
            <%= build_kachel("Suchen",requests_path, "pushpin", false) %>
            <%= build_kachel("Anbieten",requests_path, "pushpin", false) %>
            <%= build_kachel("Spenden",donations_path, "heart", false) %>
            <%= build_kachel("Belohnung",donations_path, "gift", false) %>
            <%= build_kachel("Kredit",donations_path, "signal", false) %>
            <%= build_kachel("Aktionen",showcal_action_path, "calendar", false) %>
            <%= build_kachel("Veranstaltungen",showcal_event_path, "calendar", false) %>
            <%= build_kachel("Ausschreibungen",showcal_bid_path, "calendar", false) %>

          </div>
      </div>
  </div>

app/views/home/index4.html.erb
    <%= form_for @user do |f| %>
      <%= f.text_field :address1, :id => "lat_field",  class:"form-control" %>
      <%= f.text_field :address2, :id => "lng_field",  class:"form-control" %>
    <% end %>

    <div id="map">
    </div>

    <script>
      // Note: This example requires that you consent to location sharing when
      // prompted by your browser. If you see the error "The Geolocation service
      // failed.", it means you probably did not give permission for the browser to
      // locate you.

      function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -34.397, lng: 150.644},
          zoom: 6
        });
        var infoWindow = new google.maps.InfoWindow({map: map});

        // Try HTML5 geolocation.
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            infoWindow.setPosition(pos);
            infoWindow.setContent('Location found.'+pos.lat+"/"+pos.lng);
            $("#lat_field").val(pos.lat);
            $("#lng_field").val(pos.lng);
            map.setCenter(pos);
          }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
          });
        } else {
          // Browser doesn't support Geolocation
          handleLocationError(false, infoWindow, map.getCenter());
        }
      }

      function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
                              'Error: The Geolocation service failed.' :
                              'Error: Your browser doesn\'t support geolocation.');
      }
    </script>
    
<script>
   $(document).ready(function(){
    $("#lat_field").val(pos.lat);
    $("#lng_field").val(pos.lng);
   });
</script>

app/views/home/index5.html.erb
  <div class="row">
    <div class="col-md-12">
      <div class="panel-heading header">
        <li_header>
          STATISTIK Betrag
        </li_header>
      </div>
      <div class="panel-body">
        <%= content_tag :div, "", id: "reports_chart_anz",  data: {reports: @test} %>
      </div>
    </div>  
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="panel-heading header">
        <li_header>
          STATISTIK Betrag
        </li_header>
      </div>
      <div class="panel-body">
        <%= content_tag :div, "", id: "donut-example0", data: {reports: @array} %>
      </div>
    </div>  
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="panel-heading header">
        <li_header>
          STATISTIK Betrag
        </li_header>
      </div>
      <div class="panel-body">
        <%= content_tag :div, "", id: "donut-example1", data: {reports:[{label: "Status ok", value: 12},
                                                                        {label: "Status nok", value: 30},
                                                                        {label: "Status in Prüfung", value: 20}]} %>
      </div>
    </div>  
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="panel-heading header">
        <li_header>
          STATISTIK Betrag
        </li_header>
      </div>
      <div class="panel-body">
        <%= content_tag :div, "", id: "donut-example2" %>
      </div>
    </div>  
  </div>

<script>
new Morris.Bar({
        element: 'reports_chart_anz',
        data: $('#reports_chart_anz').data('reports'),
        xkey: 'datum', 
        ykeys: ['summe'], 
        labels: ['Anzahl']
});
</script>

<script>
Morris.Donut({
  element: 'donut-example0',
  data: $('#donut-example0').data('reports'),
});
</script>

<script>
Morris.Donut({
  element: 'donut-example1',
  data: $('#donut-example1').data('reports'),
});
</script>

<script>
Morris.Donut({
  element: 'donut-example2',
  data: [
    {label: "Download Sales", value: 12},
    {label: "In-Store Sales", value: 30},
    {label: "Mail-Order Sales", value: 20}
  ],
  colors: ['red',
            'blue',
            'green'
  ]
});
</script>

app/views/home/index6.html.erb
  <div class="row">
    <header>
    <%= header("Meine Abfragen", true) %>
    </header>
  </div>
  <div class="row">
      <div class='col-xs-12'>
          <div class="panel-body">
            <% current_user.searches.order(:search_domain).each do |s| %>
            
                <% case s.search_domain %>
                  <% when "Privatpersonen" %>
                    <% path = users_path(:filter_id => s.id) %>
                    <% pic = "user" %>
                    <% pic = "user.jpg" %>
                  <% when "Institutionen" %>
                    <% path = companies_path(:filter_id => s.id) %>
                    <% pic = "copyright-mark" %>
                    <% pic = "company.jpg" %>
                  <% when "Angebote" %>
                    <% path = services_path(:filter_id => s.id, :stype => "regular") %>
                    <% pic = "shopping-cart" %>
                    <% pic = "service.jpg" %>
                  <% when "Aktionen" %>
                    <% path = services_path(:filter_id => s.id, :stype => "action") %>
                    <% pic = "time" %>
                    <% pic = "aktion.jpg" %>
                  <% when "Mobilien" %>
                    <% path = vehicles_path(:filter_id => s.id) %>
                    <% pic = "retweet" %>
                    <% pic = "vehicle.png" %>
                  <% when "Ausschreibungen" %>
                    <% path = bids_path(:filter_id => s.id) %>
                    <% pic = "pencil" %>
                    <% pic = "bid.jpg" %>
                  <% when "Kleinanzeigen" %>
                    <% path = requests_path(:filter_id => s.id , :rtype => s.rtype) %>
                    <% pic = "pushpin" %>
                    <% pic = "kleinanzeigen.jpg" %>
                  <% when "Stellenanzeigen" %>
                    <% path = jobs_path(:filter_id => s.id) %>
                    <% pic = "briefcase" %>
                    <% pic = "stellenanzeigen.jpg" %>
                  <% when "Veranstaltungen" %>
                    <% path = events_path(:filter_id => s.id) %>
                    <% pic = "glass" %>
                    <% pic = "veranstaltungen.jpg" %>
                  <% when "Sehenswuerdigkeiten" %>
                    <% path = hotspots_path(:filter_id => s.id) %>
                    <% pic = "camera" %>
                    <% pic = "ausflug.jpg" %>
                  <% when "Spendeninitiativen" %>
                    <% path = donations_path(:filter_id => s.id, :dtype => "Donation") %>
                    <% pic = "heart" %>
                    <% pic = "spenden.jpg" %>
                  <% when "Rewardinitiativen" %>
                    <% path = donations_path(:filter_id => s.id, :dtype => "Reward") %>
                    <% pic = "gift" %>
                    <% pic = "belohnung.jpg" %>
                  <% when "Kreditinitiativen" %>
                    <% path = donations_path(:filter_id => s.id, :dtype => "Loan") %>
                    <% pic = "signal" %>
                    <% pic = "kredit.jpg" %>
                <% end %>

                <%= build_kachel(s.name, path, pic, true) if false %>
                <%= build_kachel_color(s.search_domain, s.name, path, pic, true) if true %>

            <% end %>
            
          </div>
      </div>
  </div>

app/views/home/index7.html.erb
<div class="row">
    <% @users = User.all %>
    <% @users.each do |u| %>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 ">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
                    <div class="panel panel-default" onclick="return init_map(0);">
                        <div class="row padall">
                            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                                <span></span>
                                <%= image_tag u.avatar(:medium), class:"card-img-top img-responsive" %>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                                <div class="clearfix">
                                    <div class="pull-left">
                                        <list-h1><%= u.name + " " + u.lastname %><br></list-h1>
                                    </div>
                                </div>
                                <div>
                                    <div class="pull-left">
                                        <i class="glyphicon glyphicon-map-marker"></i>
                                        <%= u.address1 %><br>
                                        <%= u.address2 %><br>
                                        <%= u.address3 %><br>
                                        <i class="glyphicon glyphicon-envelope"></i>
                                        <%= u.email %><br>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        
                        <div class="panel panel-list nopadding" onclick="return init_map(0);">
                                <br>
                                 <i class="glyphicon glyphicon-map-marker pull-left" onclick="return init_map(0);"></i>
                                 <%= link_to u do %>
                                    <i class="glyphicon glyphicon-circle-arrow-right pull-right"></i>
                                <% end %>
                                <br><br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 ">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
                    <div class="panel panel-default" onclick="return init_map(0);">
                        <div class="row padall">
                            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                                <span></span>
                                <%= image_tag User.find(1).avatar(:medium), class:"card-img-top img-responsive" %>
                                <img src="/Content/images/shared/properties1/condo1.jpg" />
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
                                <div class="clearfix">
                                    <div class="pull-left">
                                        <span class="fa fa-dollar icon">499,000</span>
                                    </div>
                                    <div class="pull-right">
                                        900 SqFt | 1 Bedroom | 1 Bathroom
                                    </div>
                                </div>
                                <div>
                                    <h4><span class="fa fa-map-marker icon"></span>1021 N Garfield St</h4>
                                    Build 2007. Close to Merto.<span class="fa fa-lock icon pull-right">   Sold</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
                    <div class="panel panel-primary" onclick="javascript:init_map(1);">
                        <div class="row padall">
                            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                                <span></span>
                                <%= image_tag User.find(2).avatar(:medium), class:"card-img-top img-responsive" %>
                                <img src="/Content/images/shared/properties1/condo2.jpg" />
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
                                <div class="clearfix">
                                    <div class="pull-left">
                                        <span class="fa fa-dollar icon">$385,000</span>
                                    </div>
                                    <div class="pull-right">
                                        1,135 SqFt | 2 Bedrooms | 2 Bathrooms                                
                                    </div>
                                </div>
                                <div>
                                    <h4><span class="fa fa-map-marker icon"></span>4195 S Four Mile Run Dr</h4>
                                    Build 2001. Fully refurbished.<span class="fa fa-search icon pull-right">   More</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
                    <div class="panel panel-primary" onclick="return init_map(2);">
                        <div class="row padall">
                            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                                <span></span>
                                <%= image_tag User.find(3).avatar(:medium), class:"card-img-top img-responsive" %>
                                <img src="/Content/images/shared/properties1/house1.jpg" />
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
                                <div class="clearfix">
                                    <div class="pull-left">
                                        <span class="fa fa-dollar icon">675, 000</span>
                                    </div>
                                    <div class="pull-right">
                                        1,196 SqFt | 3 Bedrooms | 1 Bathroom                                
                                    </div>
                                </div>
                                <div>
                                    <h4><span class="fa fa-map-marker icon"></span>5108 24th St N</h4>
                                    Build 2011. Fully Furnished.<span class="fa fa-search icon pull-right">   More</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
                    <div class="panel panel-primary" onclick="return init_map(3);">
                        <div class="row padall">
                            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                                <span></span>
                                <%= image_tag User.find(4).avatar(:medium), class:"card-img-top img-responsive" %>
                                <img src="/Content/images/shared/properties1/house2.jpg" />
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
                                <div class="clearfix">
                                    <div class="pull-left">
                                        <span class="fa fa-dollar icon">945,000</span>
                                    </div>
                                    <div class="pull-right">
                                        3,500 SqFt | 5 Bedrooms | 3 Bathrooms  
                                    </div>
                                </div>
                                <div>
                                    <h4><span class="fa fa-map-marker icon"></span>2717 S Arlington Ridge Rd</h4>
                                    Build 2012. Call for availability.<span class="fa fa-search icon pull-right">   More</span>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <div class="row padbig">
                <div id="map" class="map">
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var latitudes = [38.885516, 38.898537, 38.8507126, 38.84753];
    var longitudes = [-77.09327200000001, -77.13208299999997, -77.09903600000001, -77.06577290000001];

    function init_map(index) {
        var myLocation = new google.maps.LatLng(latitudes[index], longitudes[index]);
        var mapOptions = {
            center: myLocation,
            zoom: 16
        };
        var marker = new google.maps.Marker({
            position: myLocation,
            title: "Property Location"
        });
        var map = new google.maps.Map(document.getElementById("map"),
            mapOptions);
        marker.setMap(map);
    }

    init_map(0);
</script>