config/routes.rb
Rails.application.routes.draw do

  resources :user_positions
  get 'customer_advisor/index'
  get 'customer_advisor/index2'
  
  get 'listaccounts/index'

  get 'statement/index'

  resources :transactions
  resources :accounts
  resources :emails
  resources :appointment_documents
  resources :service_documents
  resources :appointments
  resources :advisors
  resources :partner_links
  get 'ticketuserview/index'
  get 'ticketuserview/index2'
  get 'users/ticketstatus'

  resources :user_tickets
  resources :tickets
  resources :customers
  get 'showcal/action'

  get 'showcal/bid'

  get 'showcal/event'

  resources :bid_documents
  resources :hs_ratings
  resources :hotspot_details
  resources :hotspots
  resources :favourits
  get 'ticker/index'

  resources :appparams
  get 'offer/index'
  get 'home/index2'
  get 'home/index3'
  get 'home/index4'
  get 'home/index5'
  get 'home/index6'  
  get 'home/index7'  
  resources :webmasters
  resources :bid_details
  resources :bids
  resources :jobs
  resources :donation_stats
  resources :donation_details
  resources :donations
  resources :sponsors
  resources :event_details
  resources :events
  devise_for :users, :controllers => {registrations: 'registrations'}

  resources :companies
  resources :users
  resources :searches
  resources :services
  resources :calenders
  resources :vehicles
  resources :request_details
  resources :requests
  resources :ratings
  resources :searches

  root 'home#index3'
  get 'admin/sendmail'
  get 'admin/showmap'
  get 'home/index'
  post 'home/index'
  get 'home/dashboard'
  post 'home/dashboard'
  get 'users/index' 
  get 'users/workorder'
  get 'companies/search'
  

end

app/models/rating.rb
class Rating < ActiveRecord::Base
    
    belongs_to :user
    belongs_to :service
    
    validates_inclusion_of :user_rating, :in => 1..5
    
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]
  permits :status, :user_id, :service_id, :user_comment, :user_rating, :anbieter_comment, :anbieter_rating

  # GET /ratings
  def index
    if params[:service_id] != nil
      session[:service_id] = params[:service_id]
    end
    @ratings = Rating.where("service_id=?", params[:service_id]).order(:created_at).page(params[:page]).per_page(10)
  end

  # GET /ratings/1
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
    @rating.service_id = params[:service_id]
    @rating.user_id = current_user.id
    @rating.created_at = Date.today
    @rating.anbieter_rating = 0
    @rating.user_rating = 0
    @rating.status = "new"
  end

  # GET /ratings/1/edit
  def edit
    @rating.status = "changed"
  end

  # POST /ratings
  def create(rating)
    @rating = Rating.new(rating)
    if @rating.save
      redirect_to service_path(:id => @rating.service, :topic => "Servicerating"), notice: 'Rating was successfully created.'
    else
      render :new
    end
  end

  # PUT /ratings/1
  def update(rating)
    if @rating.update(rating)
      redirect_to user_path(:id => @rating.user_id, :topic => "Rating"), notice: 'Rating was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /ratings/1
  def destroy
    @us = @rating.user_id
    @rating.destroy
    redirect_to user_path(:id => @us, :topic => "Rating"), notice: 'Rating was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating(id)
      @rating = Rating.find(id)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
    <%= form_for @rating do |f| %>

        <% if @rating.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>
              <ul>
                  <% @rating.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
              </ul>
            </div>
        <% end %>

        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading header">
                      <li_header>
                      <%= link_to @rating.service do %>
                        <i class="btn btn-primary btn-lg glyphicon glyphicon-list"></i>
                      <% end %>
                      BEWERTUNG <%= @rating.service.name %>
                      </li_header>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
              <div class="col-md-6">
                  <div class="panel-body">
                    
                    <% if !session[:anbieter_rating] %> 
                        <div class="form-group">
                          <%= f.label "Benutzerbewertung" %><br/>
                          <% for i in 1..5 %>
                              <%= f.radio_button :user_rating, i.to_i %>
                              <% i.times do %>
                                <% image_tag("rating_star.jpg", :size => "50x50" , class:"img-rounded") %>
                                <i class="glyphicon glyphicon-star"></i>
                              <% end %><br>
                          <% end %>
                          <%= f.text_area :user_comment, rows: 3, class:"form-control"%>
                        </div>
                        <div class="form-group">
                          <%= f.label "Anbieterbewertung" %><br/>
                          <% if @rating.anbieter_rating != nil %>
                            <% @rating.anbieter_rating.times do %>
                              <% image_tag("rating_star.jpg", :size => "50x50" , class:"img-rounded") %>
                              <i class="glyphicon glyphicon-star"></i>
                            <% end %><br>
                          <% end %>
                          <%= f.text_area :anbieter_comment, :readonly => true, rows: 3, class:"form-control"%>
                        </div>
                    <% else %>
                        <div class="form-group">
                          <%= f.label "Benutzerrating" %><br/>
                          <% @rating.user_rating.times do %>
                            <% image_tag("rating_star.jpg", :size => "50x50" , class:"img-rounded") %>
                              <i class="glyphicon glyphicon-star"></i>
                            <% end %><br>
                          <%= f.text_area :user_comment, :readonly => true, rows: 3, class:"form-control"%>
                        </div>
                        <div class="form-group">
                          <%= f.label "Anbieterrating" %><br/>
                          <% for i in 1..5 %>
                              <%= f.radio_button :anbieter_rating, i.to_i %>
                              <% i.times do %>
                                <% image_tag("rating_star.jpg", :size => "50x50" , class:"img-rounded") %>
                                <i class="glyphicon glyphicon-star"></i>
                              <% end %><br>
                          <% end %>
                          <%= f.text_field :anbieter_comment, rows: 3, class:"form-control"%>
                        </div>
                    <% end %>

                     <%= f.hidden_field :user_id, class:"form-control" %>
                     <%= f.hidden_field :service_id, class:"form-control" %>
                     <%= f.hidden_field :created_at, class:"form-control" %>
                    <div class="actions">
                      <%= f.submit "Speichern",  class:"btn btn-primary btn-lg"%>
                    </div>
                </div>
            </div>
        </div>
    <% end %>

app/views/ratings/index.html.erb
	<div class="row">
    <div class="col-md-12">
      <div class="panel panel-info">
        <div class="panel-heading">

          <% if session[:mode] == "company" %>
            <%= link_to services_path :page => session[:page], :stype => session[:stype], :mode => "company", :company_id => session[:company_id] do %>
              <i class="btn btn-primary glyphicon glyphicon-list"></i>
            <% end %>
          <% end %>
          <% if session[:mode] == "private" %>
            <%= link_to services_path :page => session[:page], :stype => session[:stype], :mode => "private", :user_id => session[:user_id] do %>
              <i class="btn btn-primary glyphicon glyphicon-list"></i>
            <% end %>
          <% end %>

          <% if user_signed_in? %>
            <%= link_to new_rating_path(:user_id => current_user.id, :service_id => session[:service_id]) do %>
              <i class="btn btn-primary glyphicon glyphicon-plus"></i>
            <% end %>
          <% end %>

          <%= form_tag ratings_path, :method => "get" do %>
            <div class="row">
              <div class="col-md-4">
                <%= text_field_tag :search, params[:search], class:"form-control" %>
              </div>
              <div class="col-md-1">
                <%= submit_tag "Suche", :name => nil, class:"btn btn-primary btn-lg" %>
              </div>
              <div class="col-md-1">
                <%= link_to "Suche (erweitert)", new_search_path, class:"btn btn-default btn-lg" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
	<div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
    		<!--<table class="table table-striped table-hover-->
    		<table class="table table-striped">
          <thead>
            
            <tr>
              <td colspan="13">
                <div class="digg_pagination">
                    <%= will_paginate @ratings, :container => false, previous_label: "<", next_label: ">" %>
                </div>	  
              </td>
            </tr>
            
            <tr>
              <th>Datum</th>
              <th colspan="4">Rating Nutzer</th>
              <th colspan="2">Rating Serviceerbringer</th>
              <th></th>
            </tr>
          </thead>
        
          <tbody>
            <% @ratings.each do |rat| %>
              <tr>
                
                <td><%= rat.created_at.strftime("%d.%m.%Y") %></td>
                <td>
                <% if !rat.user.avatar_file_name %>
                  <%= image_tag("user_a.png", :size => "50x50" , class:"img-rounded") %>
                <% else %>
                  <%= image_tag rat.user.avatar(:small), class:"img-rounded" %>
                <% end %>
                </td>
                <td><%= rat.user.name + " " + rat.user.lastname %></td>
                <td>
                  <% if rat.user_rating != %>
                    <% rat.user_rating.times do %>
                      <%= image_tag("rating_star.jpg", :size => "50x50" , class:"img-rounded") %>
                    <% end %>
                  <% end %>
                </td>
                <td><%= rat.user_comment %></td>

                <td>
                  <% if rat.anbieter_rating != nil %>
                    <% rat.anbieter_rating.times do %>
                      <%= image_tag("rating_star.jpg", :size => "50x50" , class:"img-rounded") %>
                    <% end %>
                  <% end %>
                </td>
                <td><%= rat.anbieter_comment %></td>

                <td>
                  <ul class="nav nav-pills">
        				    <% if rat.user_id == current_user.id %>
          	          <li>
          				        <%= link_to edit_rating_path(rat) do %>
                            <i class="btn btn-default glyphicon glyphicon-wrench"></i>
                          <% end %>
          				    </li>
              	      <li>
          				        <%= link_to rat, method: :delete, data: { confirm: 'Are you sure?' } do %>
                            <i class="btn btn-danger glyphicon glyphicon-trash"></i>
                          <% end %>
          				    </li>
          				  <% end %>
        			    </ul>
                </td>

              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/ratings/new.html.erb
<%= render 'form' %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @rating.user_id %>
</p>

<p>
  <strong>Service:</strong>
  <%= @rating.service_id %>
</p>

<p>
  <strong>User comment:</strong>
  <%= @rating.user_comment %>
</p>

<p>
  <strong>User rating:</strong>
  <%= @rating.user_rating %>
</p>

<p>
  <strong>Anbieter comment:</strong>
  <%= @rating.anbieter_comment %>
</p>

<p>
  <strong>Anbieter rating:</strong>
  <%= @rating.anbieter_rating %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>