config/routes.rb
Rails.application.routes.draw do

  resources :user_positions
  get 'customer_advisor/index'
  get 'customer_advisor/index2'
  
  get 'listaccounts/index'

  get 'statement/index'

  resources :transactions
  resources :accounts
  resources :emails
  resources :appointment_documents
  resources :service_documents
  resources :appointments
  resources :advisors
  resources :partner_links
  get 'ticketuserview/index'
  get 'ticketuserview/index2'
  get 'users/ticketstatus'

  resources :user_tickets
  resources :tickets
  resources :customers
  get 'showcal/action'

  get 'showcal/bid'

  get 'showcal/event'

  resources :bid_documents
  resources :hs_ratings
  resources :hotspot_details
  resources :hotspots
  resources :favourits
  get 'ticker/index'

  resources :appparams
  get 'offer/index'
  get 'home/index2'
  get 'home/index3'
  get 'home/index4'
  get 'home/index5'
  get 'home/index6'  
  get 'home/index7'  
  resources :webmasters
  resources :bid_details
  resources :bids
  resources :jobs
  resources :donation_stats
  resources :donation_details
  resources :donations
  resources :sponsors
  resources :event_details
  resources :events
  devise_for :users, :controllers => {registrations: 'registrations'}

  resources :companies
  resources :users
  resources :searches
  resources :services
  resources :calenders
  resources :vehicles
  resources :request_details
  resources :requests
  resources :ratings
  resources :searches

  root 'home#index3'
  get 'admin/sendmail'
  get 'admin/showmap'
  get 'home/index'
  post 'home/index'
  get 'home/dashboard'
  post 'home/dashboard'
  get 'users/index' 
  get 'users/workorder'
  get 'companies/search'
  

end

app/models/donation.rb
class Donation < ActiveRecord::Base
    belongs_to :company
    belongs_to :user
    has_many :donation_details, dependent: :destroy 
    has_many :donation_stats, dependent: :destroy 
    
    def self.search(filter, search, dtype)
      if filter
            @search = Search.find(filter)
            where(@search.build_sql)
      else
        if search
          where('dtype=? and active=? and stichworte LIKE ? OR name LIKE ?', dtype, true, "%#{search}%", "%#{search}%")
        else
          where('dtype=? and active=?', dtype, true)
        end
      end 
    end
    
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]
  permits :date_from, :date_to, :due_date, :interest_rate, :days,:status, :name, :description, :user_id, :company_id, :amount, :active, :stichworte, :dtype, :price, :reward

  # GET /donations
  def index
    session[:page] = params[:page]
    @donations = Donation.search(params[:filter_id], params[:search], params[:dtype]).order(created_at: :desc).page(params[:page]).per_page(10)
    @donanz = @donations.count
    @dtype = params[:dtype]
  end

  # GET /donations/1
  def show

    @donstats_anz = DonationStat.select("date(created_at) as datum, count(amount) as summe").where('donation_id = ?', @donation.id).group("date(created_at)")
    
    @donstats_bet = DonationStat.select("date(created_at) as datum, sum(amount) as summe").where('donation_id = ?', @donation.id).group("date(created_at)")
    
    @dtype = @donation.dtype
    
    if params[:donation_trx_id]
      @donation = Donation.find(params[:donation_trx_id])
      @donation.donation_stats.each do |ds|

        @trx = Transaction.new
        @trx.ttype = "Payment"
        @trx.user_id = ds.user_id
        @trx.company_id = ds.company_id
        @trx.account_bel = getKonto(ds.user_id, ds.company_id, "Belastung")
        @trx.account_ver = getKonto(ds.donation.user_id, ds.donation.company_id, "Verguetung")
        @trx.trx_date = Date.today 
        @trx.valuta = Date.today+1
        @trx.status = "erfasst"
        @trx.active = true
        @trx.object_name = "Donation"
        @trx.object_id = @donation.id
        @trx.ref =
        @trx.text = 
        @trx.amount = ds.amount
        if @trx.account_bel and @trx.account_ver
          @trx.save
        end

      end
    end
     if params[:topic]
       @topic = params[:topic]
     else 
       @topic = "Donationinformation"
     end 
    
  end

  # GET /donations/new
  def new
    @donation = Donation.new
    if params[:dtype]
      @donation.dtype = params[:dtype]
    end
    if params[:company_id]
      @donation.company_id = params[:company_id]
    end
    if params[:user_id]
      @donation.user_id = params[:user_id]
    end
    @donation.amount = 0
    @donation.price = 0
    @donation.interest_rate = 0
    @donation.active = true
    @donation.status = "new"
    @donation.date_from = Date.today
    @donation.date_to = Date.today + 90
    @donation.due_date = @donation.date_to + 365
  end

  # GET /donations/1/edit
  def edit
    @donation.status = "changed"
  end

  # POST /donations
  def create(donation)
    @donation = Donation.new(donation)
    if @donation.save
      if @donation.user_id
        redirect_to user_path(:id => @donation.user_id, :topic => @donation.dtype), notice: 'Reward was successfully created.'
      end
      if @donation.company_id
        redirect_to company_path(:id => @donation.company_id, :topic => @donation.dtype), notice: 'Reward was successfully created.'
      end
    else
      render :new
    end
  end

  # PUT /donations/1
  def update(donation)
    if @donation.update(donation)
      redirect_to @donation, :page => session[:page], notice: 'Crowd Initiative was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /donations/1
  def destroy
    @dtype = @donation.dtype
    @us = @donation.user_id
    @comp = @donation.company_id
    @donation.destroy
    if @us
      redirect_to user_path(:id => @us, :topic => @donation.dtype), notice: 'Crowd Initiative was successfully destroyed.'
    end
    if @comp
      redirect_to company_path(:id => @comp, :topic => @donation.dtype), notice: 'Crowd Initiative was successfully destroyed.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation(id)
      @donation = Donation.find(id)
    end
    
    def getKonto(user_id, company_id, type)
    
    if user_id
      @user = User.find(user_id)
      @ali = []
      @partners = Company.where('partner=?',true)
      @partners.each do |p|
        @customer = Customer.where("user_id=? AND partner_id=?", user_id, p.id).first
        if @customer
          case type
            when "Belastung"
              @customer.accounts.each do |ca|
                @ali << ca.id
              end
            when "Verguetung"
              @customer.accounts.where('is_account_ver=?',true).each do |ca|
                @ali << ca.id
              end
          end
        end
      end
    end
    
    if company_id
      @company = Company.find(company_id)
      @ali = []
      @partners = Company.where('partner=?',true)
      @partners.each do |p|
        @customer = Customer.where("company_id=? AND partner_id=?", company_id, p.id).first
        if @customer
          case type
            when "Belastung"
              @customer.accounts.each do |ca|
                @ali << ca.id
              end
            when "Verguetung"
              @customer.accounts.where('is_account_ver=?',true).each do |ca|
                @ali << ca.id
              end
          end
        end
      end
    end
    
    puts type + " " + @ali.to_s
    return @ali[0]
  end

end

app/helpers/donations_helper.rb
module DonationsHelper
    

end

app/views/donations/_form.html.erb
  <%= form_for @donation do |f| %>
     <div class="row">
        <div class="col-md-9">
          <div class="panel panel-heading header">
            <h1>
            <%= link_to donations_path :dtype => @donation.dtype, :page => session[:page] do %>
              <i class="btn btn-primary glyphicon glyphicon-list"></i>
            <% end %>
            <% if @donation.dtype == "Donation" %>
              SPENDENINITIATIVE
            <% end %>
            <% if @donation.dtype == "Reward" %>
              CROWDFUNDING mit Belohnung 
            <% end %>
            <% if @donation.dtype == "Loan" %>
              CROWDFUNDING mit Verzinsung
            <% end %>
            </h1>
          </div>
        </div>
     </div>

     <div class="row">
        <div class="col-md-9">
          <div class="panel-body">
            <% if @donation.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this workorder from being saved:</h2>
                <ul>
                  <% @donation.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="form-group">
              <%= f.label "Bezeichnung" %><br/>
              <%= f.text_field :name, autofocus: true, class:"form-control"%>
            </div>
            <div class="form-group">
              <%= f.label "Beschreibung" %><br/>
              <%= f.text_area :description, rows: 5, class:"form-control"%>
            </div>
            <% if @donation.dtype == "Reward" %>
            <% end %>
            <div class="form-group">
              <% f.label "Organisation" %><br/>
                <% f.collection_select :company_id, Company.where('active=? and social=? and user_id=?',true,true, current_user.id), :id, :name, {}, :readonly => true, class:"form-control" %>
            </div>
            <div class="field">
              <%= f.label :Betrag %><br>
              <%= f.number_field :amount , class:"form-control" %>
            </div>
            <div class="form-group">
              <%= f.label "Laufzeit Initiative von-bis" %><br/>
              <%= f.text_field :date_from, class:"form-control"%>
              <%= f.text_field :date_to, class:"form-control"%>
            </div>
            <% if @donation.dtype == "Reward" %>
              <div class="form-group">
                <%= f.label "Reward" %><br/>
                <%= f.text_field :reward, class:"form-control"%>
              </div>
              <div class="form-group">
                <%= f.label "Stückelung" %><br/>
                <%= f.text_field :price, class:"form-control"%>
              </div>
            <% end %>
            <% if @donation.dtype == "Loan" %>
              <div class="field">
                <%= f.label "Zinssatz" %><br>
                <%= f.number_field :interest_rate , class:"form-control" %>
              </div>
              <div class="form-group">
                <%= f.label "Laufzeit Kredit" %><br/>
                <%= f.text_field :due_date, class:"form-control"%>
              </div>
            <% end %>
            <div class="form-group">
              <%= f.label "Stichworte" %><br/>
              <%= f.text_field :stichworte, class:"form-control"%>
            </div>
            <div class="field">
              <input type="checkbox" name="my-checkbox1" checked>
              <%= f.label :Aktiv %><br>
            </div>
            <div class="actions">
              <%= f.submit "Speichern", class:"btn btn-primary btn-lg"%>
            </div>
            <%= f.hidden_field :company_id, class:"form-control"%>
            <%= f.hidden_field :user_id, class:"form-control"%>
            <%= f.hidden_field :dtype, class:"form-control"%>
          </div>
              <%= f.check_box :active, :id => "active", class:"form-control hidden" %>
        </div>
      </div>
      
  <% end %>

<script>
     $.fn.bootstrapSwitch.defaults.onColor = 'success';
     $("[name='my-checkbox1']").bootstrapSwitch('state',<%= @donation.active %>);
     $("[name='my-checkbox1']").on('switchChange.bootstrapSwitch', function () {
     $("#active").prop('checked',$("[name='my-checkbox1']").bootstrapSwitch('state'));
     });
</script>

app/views/donations/index.html.erb
  
    <div class="panel-body">
      <div class="row">
        <div class="col-md-12">
          <div class="digg_pagination">
      		  <% if user_signed_in? %>
      		    <% if @dtype == "Donation" %>
    		        <%= link_to searches_path :search_domain => "Spendeninitiativen", :controller_name => controller_name do %>
    		          <i class="btn btn-primary btn-xs glyphicon glyphicon-filter"></i>
    		        <% end %>
    		      <% end %>
      		    <% if @dtype == "Reward" %>
    		        <%= link_to searches_path :search_domain => "Rewardinitiativen", :controller_name => controller_name do %>
    		          <i class="btn btn-primary btn-xs glyphicon glyphicon-filter"></i>
    		        <% end %>
    		      <% end %>
      		    <% if @dtype == "Loan" %>
    		        <%= link_to searches_path :search_domain => "Kreditinitiativen", :controller_name => controller_name do %>
    		          <i class="btn btn-primary btn-xs glyphicon glyphicon-filter"></i>
    		        <% end %>
    		      <% end %>
      		  <% end %>
            <%= will_paginate @donations, :container => false, previous_label: "<", next_label: ">" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <% if @dtype == "Donation" %>
      <%= header("Crowdfunding Spenden " + "<span class='badge'>" + @donanz.to_s + "</span>", true) %>
    <% end %>
    <% if @dtype == "Reward" %>
      <%= header("Crowdfunding Belohnung " + "<span class='badge'>" + @donanz.to_s + "</span>", true) %>
    <% end %>
    <% if @dtype == "Loan" %>
      <%= header("Crowdfunding Kredit " + "<span class='badge'>" + @donanz.to_s + "</span>", true) %>
    <% end %>
  </div>
  
  <%= build_medialist("col-sm-6 col-md-4 col-lg-3", @donations, "donations", true) if false %>

  <%= build_medialist2(@donations, "donations") %>

app/views/donations/new.html.erb
<%= render 'form' %>

app/views/donations/show.html.erb
  <div class="row">
    <action>
    <%= action_buttons("Donation", @donation, @topic) %>
    </action>
  </div>

  <div class="row">
    <header>
    <% case @dtype %>
      <% when "Donation" %>
        <%= header("Crowdfunding (Spende) " + @donation.name, true) %>
      <% when "Reward" %>
        <%= header("Crowdfunding (Reward) " + @donation.name, true) %>
      <% when "Loan" %>
        <%= header("Crowdfunding (Kredit) " + @donation.name, true) %>
    <% end %>
    </header>
  </div>
  
  <div class="row">
      <div class='col-xs-10'>

      <% case @topic %>
        <% when "Donationinformation" %>
          <%= header("Informationen", false) %>
          <div class="panel-body">
            <%= carousel2(@donation.donation_details, :medium) %>
      			</p>
            <b>Beschreibung</b><br>
      			<%= @donation.description %>
            <br><br>
            <% case @donation.dtype %>
              <% when "Donation" %>
                <b>Spendenziel</b><br>
                <%= sprintf("%05.2f CHF", @donation.amount) %>
                <br>
              <% when "Reward" %>
                <b>Projektziel</b><br>
                <%= sprintf("%05.2f CHF", @donation.amount) %>
                <br><br>
                <b>Stückelung</b><br>
                <%= sprintf("%05.2f CHF", @donation.price) %>
                <br><br>
                <b>Belohnung</b><br>
                <%= @donation.reward %>
                <br>
              <% when "Loan" %>
                <b>Kreditsumme</b><br>
                <%= sprintf("%05.2f CHF", @donation.amount) %>
                <br><br>
                <b>Zinssatz</b><br>
                <%= @donation.interest_rate %>%
                <br><br>
                Rückzahlung am <%= @donation.due_date.strftime("%d.%m.%Y") %>
                <br>
            <% end %>
            <br>
            <b>initialisiert von:</b><br>
            <% if @donation.company_id %>
              <%= showImage("Company", :small, @donation.company) %>
              <%= @donation.company.name %>
            <% end %>
            <% if @donation.user_id %>
              <%= showImage("User", :small, @donation.user) %>
              <%= @donation.user.name + " " + @donation.user.lastname %>
            <% end %>
      			<br><br>
            <%= @donation.created_at.strftime("%d.%m.%Y") %>
          </div>
      <% end %>

      <% case @topic %>
        <% when "Donationdetail" %>
          <%= header("Informationen", false) %>
          <div class="panel-body">
        		<% @donation.donation_details.each do |bd| %>
              <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="thumbnail" align="center">
          				<% if bd.avatar_file_name == nil %>
                    <%= image_tag("donation_a.png", :size => "200x200", class:"img-rounded" ) %>
                  <% else %>
                    <%= image_tag bd.avatar(:medium), class:"img-rounded"  %>
                  <% end %>
                  <br>
                  <anzeigetext>
        						<%= bd.name %><br>
                  </anzeigetext>
                  <ntext>
      						<%= bd.description %>
                  </ntext>
                  <br>
                  <% if user_signed_in? %>
                  <% if (@donation.company_id and current_user.id == @donation.company.user_id) or (@donation.user_id and current_user.id == @donation.user_id) %>
            	        <%= link_to edit_donation_detail_path(bd) do %>
                        <i class="btn btn-primary btn-lg glyphicon glyphicon-wrench"></i>
                      <% end %>
            	        <%= link_to bd, method: :delete, data: { confirm: 'Are you sure?' } do %>
                        <i class="btn btn-danger btn-lg glyphicon glyphicon-trash"></i>
                      <% end %>
                    <% end %>
                  <% end %>
                  <br><br>
        			  </div>
        			</div>
        		<% end %>
          </div>
      <% end %>

      <% case @topic %>
        <% when "Donationstatistikanz" %>
          <%= header("Statistik (Anzahl)", false) %>
          <div class="panel-body">
              <%= content_tag :div, "", id: "reports_chart_anz",  data: {reports: @donstats_anz} %>
          </div>
      <% end %>

      <% case @topic %>
        <% when "Donationstatistiksum" %>
          <%= header("Statistik (Betrag)", false) %>
          <div class="panel-body">
            <%= content_tag :div, "", id: "reports_chart_bet",  data: {reports: @donstats_bet} %>
          </div>
      <% end %>

      <% case @topic %>
        <% when "Donationstat" %>
          <%= header("Transaktionen", false) %>
          <div class="panel-body">
            <% @donation.donation_stats.order(amount: :desc).each do |ds| %>
              <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="thumbnail" align="center">
        				  <% if ds.company_id != nil %>
                    <%= link_to ds.company do %>
              				<% if ds.company.avatar_file_name == nil %>
                        <%= image_tag("company_a.png", :size => "200x200", class:"img-rounded" ) %>
                      <% else %>
                        <%= image_tag ds.company.avatar(:medium), class:"img-rounded"  %>
                      <% end %><br>
                    <% end %>
          				  <%= ds.company.name %>
          				<% end %>
          				<% if ds.user_id != nil %>
          				  <%= link_to ds.user do %>
              				<% if ds.user.avatar_file_name == nil %>
                        <%= image_tag("user_a.png", :size => "200x200", class:"img-rounded" ) %>
                      <% else %>
                        <%= image_tag ds.user.avatar(:medium), class:"img-rounded"  %>
                      <% end %><br>
                    <% end %>
          				  <%= ds.user.name + " " + ds.user.lastname  %>
          				<% end %>
          				<br><br>
          				<% if !ds.anonymous %>
          	        <% if ds.donation.dtype == "Donation" %>
                      <ntext>Spendenbetrag</ntext><br><preis><%= sprintf("%05.2f CHF", ds.amount) %></preis><ntext><br> am <%= ds.created_at.strftime("%d.%m.%Y") %></ntext>
                      <br><br>
                    <% end %>
          	        <% if ds.donation.dtype == "Reward" %>
                      <ntext>Unterstützungsbetrag</ntext><br><preis><%= sprintf("%05.2f CHF", ds.amount) %></preis><ntext><br> am <%= ds.created_at.strftime("%d.%m.%Y") %></ntext>
                      <br><br>
                    <% end %>
          	        <% if ds.donation.dtype == "Loan" %>
                      <ntext>Kreditbetrag</ntext><br><preis><%= sprintf("%05.2f CHF", ds.amount) %></preis><ntext><br> am <%= ds.created_at.strftime("%d.%m.%Y") %></ntext>
                      <br><br>
                    <% end %>
                  <% else %>
                      <betrag>*****.** CHF</betrag>
                  <% end %>
                  <br><br>
                  <%= ds.created_at.strftime("%d.%m.%Y") %>
                  <br><br>
                  <% if user_signed_in? %>
                    <% if (ds.user_id and current_user.id == ds.user_id) or (ds.company_id and current_user.id == ds.company.user_id) %>
    
                      <%= link_to listaccounts_index_path :user_id => current_user.id, :user_id_ver => nil, :company_id_ver => @donation.company_id, :ref => "Vergütung an "+ @donation.name, :object_name => "Donation", :object_id => @donation.id, :amount => ds.amount do %>
                        <i class="btn btn-primary glyphicon glyphicon-euro"></i>
                      <% end %>
    
            	        <%= link_to edit_donation_stat_path(ds) do %>
                        <i class="btn btn-primary glyphicon glyphicon-wrench"></i>
                      <% end %>
            	        <%= link_to ds, method: :delete, data: { confirm: 'Are you sure?' } do %>
                        <i class="btn btn-danger glyphicon glyphicon-trash"></i>
                      <% end %>
                    <% end %>
                  <% end %>
                  <br><br>
                </div>
              </div>
            <% end %>
          </div>
      <% end %>
    </div>
    
      <div class='col-xs-2'>
        <%= navigate("Donation", @donation) %>
      </div>
    
  </div>

<script>
new Morris.Line({
        element: 'reports_chart_bet',
        data: $('#reports_chart_bet').data('reports'),
        xkey: 'datum', 
        ykeys: ['summe'], 
        labels: ['Summe']
});
</script>

<script>
new Morris.Line({
        element: 'reports_chart_anz',
        data: $('#reports_chart_anz').data('reports'),
        xkey: 'datum', 
        ykeys: ['summe'], 
        labels: ['Anzahl']
});
</script>

<script type="text/javascript">
$(document).ready(function(){
  $('.bxslider').bxSlider({
      mode: 'fade',
      auto: true,
      speed:1000,
      controls: false
  });
});
</script>


<!--<script>-->
<!--$(document).ready(function(){-->
<!--  $("header").mouseenter(function() {-->
<!--    $("navigate").show();-->
<!--    $("action").show();-->
<!--  });-->
<!--})-->
<!--$(document).ready(function(){-->
<!--  $("navigate").mouseleave(function() {-->
<!--    $("navigate").hide()-->
<!--    $("action").hide();-->
<!--  });-->
<!--})</script>-->