config/routes.rb
Rails.application.routes.draw do

  resources :user_positions
  get 'customer_advisor/index'
  get 'customer_advisor/index2'
  
  get 'listaccounts/index'

  get 'statement/index'

  resources :transactions
  resources :accounts
  resources :emails
  resources :appointment_documents
  resources :service_documents
  resources :appointments
  resources :advisors
  resources :partner_links
  get 'ticketuserview/index'
  get 'ticketuserview/index2'
  get 'users/ticketstatus'

  resources :user_tickets
  resources :tickets
  resources :customers
  get 'showcal/action'

  get 'showcal/bid'

  get 'showcal/event'

  resources :bid_documents
  resources :hs_ratings
  resources :hotspot_details
  resources :hotspots
  resources :favourits
  get 'ticker/index'

  resources :appparams
  get 'offer/index'
  get 'home/index2'
  get 'home/index3'
  get 'home/index4'
  get 'home/index5'
  get 'home/index6'  
  get 'home/index7'  
  resources :webmasters
  resources :bid_details
  resources :bids
  resources :jobs
  resources :donation_stats
  resources :donation_details
  resources :donations
  resources :sponsors
  resources :event_details
  resources :events
  devise_for :users, :controllers => {registrations: 'registrations'}

  resources :companies
  resources :users
  resources :searches
  resources :services
  resources :calenders
  resources :vehicles
  resources :request_details
  resources :requests
  resources :ratings
  resources :searches

  root 'home#index3'
  get 'admin/sendmail'
  get 'admin/showmap'
  get 'home/index'
  post 'home/index'
  get 'home/dashboard'
  post 'home/dashboard'
  get 'users/index' 
  get 'users/workorder'
  get 'companies/search'
  

end

app/models/search.rb
class Search < ActiveRecord::Base
    
    serialize :sql_string, Array
    
    validates :name, presence: true
    validate :valid_ages?
    validate :upper?

    belongs_to :user

    before_validation :update_geo_address
      
    geocoded_by :geo_address
    after_validation :geocode

    def update_geo_address
      self.geo_address = self.address1 + " " + address2 + " " + address3
    end

    def upper?
        self.keywords = self.keywords.upcase
        return true
    end

      def valid_ages?
        if age_from != nil and age_to != nil
            if age_from > 0 or age_to > 0
              if age_from < age_to
                return true
              end
            end
            errors.add(:age_from, "invalid age")
        end
      end

    def build_sql
        sql_string = []
        sql_string[0] ="active=?"
        sql_string << true
        case self.search_domain
        when "Privatpersonen", "Tickets"
            sql_string[0] = sql_string[0] + " and anonymous=?"
            sql_string << false
            if self.age_from != nil and self.age_from > 0
                end_date = Date.new(Date.today.year - age_from, Date.today.month, Date.today.day)
                sql_string[0] = sql_string[0] + " and dateofbirth <=?"
                sql_string << end_date.to_s
            end
            if self.age_to != nil and self.age_to > 0 and self.age_to < 100
                start_date = Date.new(Date.today.year - age_to, Date.today.month, Date.today.day)
                sql_string[0] = sql_string[0] + " and dateofbirth >=?"
                sql_string << start_date.to_s
            end
            if self.social
                sql_string[0] = sql_string[0] + " and id IN (?)"
                @services = Service.where('social=?', 't')
                sli = []
                @services.each do |s|
                    sli << s.user_id
                end
                sql_string << sli
            end
#            if self.keywords != nil and self.keywords != ""
#                sql_string[0] = sql_string[0] + " and (name LIKE ? OR lastname LIKE ?)"
#                sql_string << "%"+self.keywords+"%"
#                sql_string << "%"+self.keywords+"%"
#            end
            if self.distance > 0 and self.longitude != nil and self.latitude != nil
                sql_string[0] = sql_string[0] + " and id IN (?)"
                @users = User.near(self.geo_address, self.distance)
                uli = []
                @users.each do |user|
                    uli << user.id
                end
                sql_string << uli
            end
            if self.search_domain == "Tickets"
                if self.customer
                    sql_string[0] = sql_string[0] + " and id IN (?)"
                    cid = Ticket.find(self.ticket_id).sponsor.company.id
                    @customers = Customer.where('company_id=?', cid)
                    cli = []
                    @customers.each do |c|
                        cli << c.user_id
                    end
                    sql_string << cli
                end
            end
            sql_string = find_keywords(sql_string, self.search_domain, self.keywords)
            self.counter = User.where(sql_string).count
            self.sql_string = sql_string

        when "Institutionen"
            if self.category_id != "" and self.category_id != nil and self.category_id.to_s.length != 0
                sql_string[0] = sql_string[0] + " and category_id=?"
                sql_string << self.category_id
            end
            if self.social == true
                sql_string[0] = sql_string[0] + " and social=?"
                sql_string << true
            end
            if self.special
                sql_string[0] = sql_string[0] + " and id IN (select company_id from services WHERE stype = 'action') "
            end
#            if self.keywords != nil and self.keywords != ""
#                sql_string[0] = sql_string[0] + " and name LIKE ?"
#                sql_string << "%" + self.keywords + "%"
#            end
            if self.distance > 0 and self.longitude != nil and self.latitude != nil
                sql_string[0] = sql_string[0] + " and id IN (?)"
                @companies = Company.near(self.geo_address, self.distance)
                cli = []
                @companies.each do |company|
                    cli << company.id
                end
                sql_string << cli
            end
            sql_string = find_keywords(sql_string, self.search_domain, self.keywords)
            self.counter = Company.where(sql_string).count
            self.sql_string = sql_string

        when "Ausschreibungen"
            if self.category_id != "" and self.category_id != nil and self.category_id.to_s.length != 0
                sql_string[0] = sql_string[0] + " and category_id=?"
                sql_string << self.category_id
            end
#            if self.keywords != nil and self.keywords != ""
#                sql_string[0] = sql_string[0] + " and name LIKE ?"
#                sql_string << "%" + self.keywords + "%"
#            end
            if self.date_from != nil and self.date_to != nil
                sql_string[0] = sql_string[0] + " and ((date_from >=?"
                sql_string << self.date_from
                sql_string[0] = sql_string[0] + " and date_to <=?)"
                sql_string << self.date_to
                sql_string[0] = sql_string[0] + " or (date_from >=?"
                sql_string << self.date_from
                sql_string[0] = sql_string[0] + " and date_to <=?))"
                sql_string << self.date_to
            end
            if self.distance > 0 and self.longitude != nil and self.latitude != nil
                sql_string[0] = sql_string[0] + " and id IN (?)"
                @users = User.near(self.geo_address, self.distance)
                uli = []
                @users.each do |user|
                    uli << user.id
                end
                sql_string << uli
            end
            sql_string = find_keywords(sql_string, self.search_domain, self.keywords)
            self.counter = Bid.where(sql_string).count
            self.sql_string = sql_string

        when "Angebote"
            sql_string[0] = sql_string[0] + "and stype=?"
            sql_string << "regular"
            if self.social == true
                sql_string[0] = sql_string[0] + " and social=?"
                sql_string << true
            end
#            if self.keywords != nil and self.keywords != ""
#                sql_string[0] = sql_string[0] + " and name LIKE ?"
#                sql_string << "%" + self.keywords + "%"
#            end
            if self.rating != nil and self.rating > 0
                sql_string[0] = sql_string[0] + " and id IN (select service_id from ratings WHERE user_rating >=?)"
                sql_string << self.rating
            end 
            if self.distance > 0 and self.longitude != nil and self.latitude != nil
                @users = User.near(self.geo_address, self.distance)
                uli = []
                @users.each do |user|
                    uli << user.id
                end
                @companies = Company.near(self.geo_address, self.distance)
                cli = []
                @companies.each do |company|
                    cli << company.id
                end
                if !uli.blank? and cli.blank?
                    sql_string[0] = sql_string[0] + " and user_id IN (?)"
                    sql_string << uli
                end
                if uli.blank? and !cli.blank?
                    sql_string[0] = sql_string[0] + " and company_id IN (?)"
                    sql_string << cli
                end
                if !uli.blank? and !cli.blank?
                    sql_string[0] = sql_string[0] + " and (company_id IN (?) or user_id IN (?))"
                    sql_string << cli
                    sql_string << uli
                end
            end
            sql_string = find_keywords(sql_string, self.search_domain, self.keywords)
            self.counter = Service.where(sql_string).count
            self.sql_string = sql_string

        when "Aktionen"
            sql_string[0] = sql_string[0] + " and stype=?"
            sql_string << "action"
#            if self.keywords != nil and self.keywords != ""
#                sql_string[0] = sql_string[0] + " and name LIKE ?"
#                sql_string << "%" + self.keywords + "%"
#            end
            if self.rating != nil and self.rating > 0
                sql_string[0] = sql_string[0] + " and id IN (select service_id from ratings WHERE user_rating >=?)"
                sql_string << self.rating
            end 
            if self.distance > 0 and self.longitude != nil and self.latitude != nil
                @users = User.near(self.geo_address, self.distance)
                uli = []
                @users.each do |user|
                    uli << user.id
                end
                @companies = Company.near(self.geo_address, self.distance)
                cli = []
                @companies.each do |company|
                    cli << company.id
                end
                if !uli.blank? and cli.blank?
                    sql_string[0] = sql_string[0] + " and user_id IN (?)"
                    sql_string << uli
                end
                if uli.blank? and !cli.blank?
                    sql_string[0] = sql_string[0] + " and company_id IN (?)"
                    sql_string << cli
                end
                if !uli.blank? and !cli.blank?
                    sql_string[0] = sql_string[0] + " and (company_id IN (?) or user_id IN (?))"
                    sql_string << cli
                    sql_string << uli
                end
            end
            sql_string = find_keywords(sql_string, self.search_domain, self.keywords)
            self.counter = Service.where(sql_string).count

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]
  permits :counter, :ticket_id, :rtype, :date_from, :date_to, :search_domain, :controller, :user_id, :name, :description, :status, :category_id, :mob_category_id, :hs_category_id, :ev_category_id, :keywords, :age_from, :age_to, :distance, :geo_address, :address1, :address2, :address3, :date_created_at, :rating, :social, :customer, :amount_from, :amount_to, :amount_from_target, :amount_to_target, :special, :rating

  # GET /searches
  def index
    if params[:search_domain]
      @search_domain = params[:search_domain]
      if @search_domain == "Spendeninitiativen"
        @dtype = "Donation"
      end
      if @search_domain == "Rewardinitiativen"
        @dtype = "Reward"
      end
    end
    if params[:controller_name]
      @controller_name = params[:controller_name]
    end
    if params[:page]
      session[:page] = params[:page]
    end
    if params[:ticket_id]
      @ticket = Ticket.find(params[:ticket_id])
      session[:sponsor_id] = @ticket.sponsor_id
      session[:ticket_id] = @ticket.id
      @searches = Search.where('ticket_id=?', params[:ticket_id]).page(params[:page]).per_page(10)

      if params[:generate]
        userticket = UserTicket.where('ticket_id=? and status=?', session[:ticket_id], "Filter Kampagne").destroy_all
        @searches.each do |s|
          @users = User.where(s.sql_string)
          @users.each do |u|
            if UserTicket.where('user_id=? and ticket_id=?', u.id, session[:ticket_id]).count == 0
              userticket = UserTicket.new
              userticket.user_id = u.id
              userticket.ticket_id = params[:ticket_id]
              userticket.status = "Filter Kampagne"
              userticket.save
            end
          end
        end
      end

      if params[:activate]
        @usertickets = UserTicket.where('ticket_id=? and status=?', session[:ticket_id], "Filter Kampagne")
        @usertickets.each do |ut|
          ut.status = "übergeben"
          ut.save
        end
      end

    else
      @searches = Search.where('search_domain=? and user_id=?', params[:search_domain], current_user.id).page(params[:page]).per_page(10)
      session[:sponsor_id] = nil
      session[:ticket_id] = nil
    end
    @seranz = @searches.count
    
  end

  # GET /searches/1
  def show
  end

  # GET /searches/new
  def new
    @search = Search.new
    @search.name = "Meine Abfrage..."+params[:search_domain]
    @search.sql_string = []
    @search.search_domain = params[:search_domain]
    @search.user_id = params[:user_id]
    @search.controller = params[:controller_name]
    @search.distance = 0
    @search.age_from = 0
    @search.age_to = 100
    @search.social = false
    @search.customer = false
    @search.special = false
    @search.amount_from_target = "10000"
    @search.amount_to_target = "50000"
    @search.amount_from = "5000"
    @search.amount_to = "10000"
    if params[:ticket_id] != nil
      @ticket = Ticket.find(params[:ticket_id])
      @search.ticket_id = @ticket.id
      @search.name = @ticket.sponsor.event.name + " Umkreissuche" 
      @search.longitude = @ticket.sponsor.event.longitude
      @search.latitude= @ticket.sponsor.event.latitude
      @search.address1 = @ticket.sponsor.event.address1
      @search.address2 = @ticket.sponsor.event.address2
      @search.address3 = @ticket.sponsor.event.address3
      @search.distance = 10
    else
      session[:ticket_id] = nil
      @search.longitude = request.location.longitude
      @search.latitude= request.location.latitude
    end
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  def create(search)
    @search = Search.new(search)
    if @search.save
      if params[:commit] == "Speichern"
        redirect_to searches_path(:user_id => current_user.id, :page => session[:page], :search_domain => @search.search_domain, :controller_name => @search.controller, :ticket_id => @search.ticket_id), notice: 'Search was successfully updated.'
      end
      if params[:commit] == "Test"
        redirect_to edit_search_path(@search), notice: 'Search successfully tested.'
      end
      if params[:commit] == nil
        redirect_to edit_search_path(@search), notice: 'Search successfully tested.'
      end
    else
      render :new
    end
  end

  # PUT /searches/1
  def update(search)
    if @search.update(search)
      if params[:commit] == "Speichern"
        redirect_to searches_path(:user_id => current_user.id, :page => session[:page], :search_domain => @search.search_domain, :controller_name => @search.controller, :ticket_id => @search.ticket_id), notice: 'Search was successfully updated.'
      end
      if params[:commit] == "Test"
        redirect_to edit_search_path(@search), notice: 'Search successfully tested.'
      end
      if params[:commit] == nil
        redirect_to edit_search_path(@search), notice: 'Search successfully tested.'
      end
    else
      render :edit
    end
  end

  # DELETE /searches/1
  def destroy
    if @search.ticket_id
      ticket_id = @search.ticket_id
    else
      ticket_id = nil
    end
    @search.destroy
    redirect_to searches_path(:user_id => current_user.id, :page => session[:page], :search_domain => @search.search_domain, :controller_name => @search.controller, :ticket_id => ticket_id), notice: 'Search was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search(id)
      @search = Search.find(id)
      @search.build_sql
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
	<div class="row">
    <div class="col-xs-12">
      <div class="panel-body">
        <% if session[:sponsor_id] != nil %>
          <%= link_to tickets_path :sponsor_id => session[:sponsor_id] do %>
            <i class="btn btn-primary glyphicon glyphicon-list"></i>
          <% end %>
          <% @counter = UserTicket.where('ticket_id=?',session[:ticket_id]).count %>
          <%= link_to searches_path :search_domain => "Tickets", :controller_name => controller_name, :ticket_id => session[:ticket_id], :activate => true, :page => session[:page] do %>
            <i class="btn btn-danger pull-right glyphicon glyphicon-user"></i>
          <% end %>
          <%= link_to searches_path :search_domain => "Tickets", :controller_name => controller_name, :ticket_id => session[:ticket_id], :generate => true, :page => session[:page] do %>
            <i class="btn btn-warning pull-right glyphicon glyphicon-user"></i>
          <% end %>
          <%= link_to ticketuserview_index_path :ticket_id => session[:ticket_id] do %>
            <i class="btn btn-primary pull-right glyphicon glyphicon-user">
            <span class="badge"><%= @counter %></span></i>
          <% end %>
        <% else %>
          <% ticket_id = nil %>
          <% if @controller_name == "donations" %>
            <%= link_to donations_path :search_domain => @search_domain, :dtype => @dtype, :page => session[:page] do %>
              <i class="btn btn-primary glyphicon glyphicon-list"></i>
            <% end %>
          <% else %>
            <%= link_to url_for(@controller_name), :search_domain => @search_domain, :dtype => @dtype, :page => session[:page] do %>
              <i class="btn btn-primary glyphicon glyphicon-list"></i>
            <% end %>
          <% end %>
        <% end %>
		    <%= link_to new_search_path(:user_id => current_user.id, :search_domain => @search_domain, :controller_name => @controller_name, :ticket_id => session[:ticket_id]) do %>
          <i class="btn btn-primary glyphicon glyphicon-plus"></i>
        <% end %>
      </div>
    </div>
  </div>
    
  <div class="row">
      <% if @ticket %>
        <%= header("Suchen " + @search_domain + " " + @ticket.sponsor.event.name + " " + @ticket.name + " <span class='badge'>" + @seranz.to_s + "</span>", true) %>
      <% else %>
        <%= header("Suchen " + @search_domain + " <span class='badge'>" + @seranz.to_s + "</span>", true) %>
      <% end %>
  </div>

	<div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
    		<!--<table class="table table-striped table-hover-->
    		<table class="table table-striped">
          <thead>
            <tr>
              <th></th>
              <th>Bezeichnung</th>
              <th>Datum</th>
              <th>Anzahl</th>
            </tr>
          </thead>
        
          <tbody>
            <% @searches.each do |s| %>
              <tr>
                <td>
                <% case s.search_domain %>
                <% when "Privatpersonen" %>
                  <%= link_to users_path :filter_id => s.id do %>
                    <i class="btn btn-primary glyphicon glyphicon-filter"></i>
                  <% end %>
                <% when "Institutionen" %>
                  <%= link_to companies_path :filter_id => s.id do %>
                    <i class="btn btn-primary glyphicon glyphicon-filter"></i>
                  <% end %>
                <% when "Angebote", "Aktionen" %>
                  <%= link_to offer_index_path :filter_id => s.id  do %>
                    <i class="btn btn-primary glyphicon glyphicon-filter"></i>
                  <% end %>
                <% when "Mobilien" %>
                  <%= link_to vehicles_path :filter_id => s.id  do %>
                    <i class="btn btn-primary glyphicon glyphicon-filter"></i>
                  <% end %>
                <% when "Ausschreibungen" %>
                  <%= link_to bids_path :filter_id => s.id  do %>
                    <i class="btn btn-primary glyphicon glyphicon-filter"></i>
                  <% end %>
                <% when "Kleinanzeigen" %>
                  <%= link_to requests_path :filter_id => s.id , :rtype => s.rtype do %>
                    <i class="btn btn-primary glyphicon glyphicon-filter"></i>
                  <% end %>
                <% when "Stellenanzeigen" %>
                  <%= link_to jobs_path :filter_id => s.id do %>
                    <i class="btn btn-primary glyphicon glyphicon-filter"></i>
                  <% end %>
                <% when "Veranstaltungen" %>
                  <%= link_to events_path :filter_id => s.id  do %>
                    <i class="btn btn-primary glyphicon glyphicon-filter"></i>
                  <% end %>
                <% when "Sehenswuerdigkeiten" %>
                  <%= link_to hotspots_path :filter_id => s.id do %>
                    <i class="btn btn-primary glyphicon glyphicon-filter"></i>
                  <% end %>
                <% when "Spendeninitiativen", "Rewardinitiativen", "Kreditinitiativen" %>
                  <%= link_to donations_path :filter_id => s.id, :dtype => @dtype  do %>
                    <i class="btn btn-primary glyphicon glyphicon-filter"></i>
                  <% end %>
                <% end %>

      	        <%= link_to edit_search_path(s, :ticket_id => ticket_id) do %>
                  <i class="btn btn-primary glyphicon glyphicon-wrench"></i>
                <% end %>
      	        <%= link_to s, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <i class="btn btn-danger glyphicon glyphicon-trash"></i>
                <% end %>
                </td>
                <td>
                  <anzeigetext>
                    <%= s.name %><br>
                  </anzeigetext>
                </td>
                <ntext>
                <td><%= s.updated_at.strftime("%d.%m.%Y um %T Uhr") %></td>
                <td><%= s.counter %></td>
                </ntext>
                </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  
  </div>


<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip(); 
});
</script>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Keywords:</strong>
  <%= @search.keywords %>
</p>

<p>
  <strong>Noga:</strong>
  <%= @search.noga %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @search.distance %>
</p>

<p>
  <strong>From lat:</strong>
  <%= @search.from_lat %>
</p>

<p>
  <strong>From lgt:</strong>
  <%= @search.from_lgt %>
</p>

<p>
  <strong>Special:</strong>
  <%= @search.special %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @search.rating %>
</p>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>